//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CacheKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CacheKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.CacheKeys", typeof(CacheKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterCategories.
        /// </summary>
        internal static string MasterCategories {
            get {
                return ResourceManager.GetString("MasterCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterEvents.
        /// </summary>
        internal static string MasterEvents {
            get {
                return ResourceManager.GetString("MasterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterGalleries.
        /// </summary>
        internal static string MasterGalleries {
            get {
                return ResourceManager.GetString("MasterGalleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterHistories.
        /// </summary>
        internal static string MasterHistories {
            get {
                return ResourceManager.GetString("MasterHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterNews.
        /// </summary>
        internal static string MasterNews {
            get {
                return ResourceManager.GetString("MasterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterPages.
        /// </summary>
        internal static string MasterPages {
            get {
                return ResourceManager.GetString("MasterPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __masterRecognitions.
        /// </summary>
        internal static string MasterRecognitions {
            get {
                return ResourceManager.GetString("MasterRecognitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterResources.
        /// </summary>
        internal static string MasterResources {
            get {
                return ResourceManager.GetString("MasterResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MasterWeights.
        /// </summary>
        internal static string MasterWeights {
            get {
                return ResourceManager.GetString("MasterWeights", resourceCulture);
            }
        }
    }
}
