//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event category is mandatory.
        /// </summary>
        internal static string EventCategoryMandatory {
            get {
                return ResourceManager.GetString("EventCategoryMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is duplicate.
        /// </summary>
        internal static string EventNameDuplidate {
            get {
                return ResourceManager.GetString("EventNameDuplidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event end date should be greater than event start date.
        /// </summary>
        internal static string EventStartDateGreaterThenEndDate {
            get {
                return ResourceManager.GetString("EventStartDateGreaterThenEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery name is duplicate.
        /// </summary>
        internal static string GalleryNameDuplidate {
            get {
                return ResourceManager.GetString("GalleryNameDuplidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History details are mandatory.
        /// </summary>
        internal static string HistoryDetailsMandatory {
            get {
                return ResourceManager.GetString("HistoryDetailsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History name is duplicate.
        /// </summary>
        internal static string HistoryNameDuplicate {
            get {
                return ResourceManager.GetString("HistoryNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username/password not correct .
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News details mandatory.
        /// </summary>
        internal static string NewsDetailsMandatory {
            get {
                return ResourceManager.GetString("NewsDetailsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page cannot be loaded due to workflow issues.
        /// </summary>
        internal static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent page makes hierarchy circular in nature.
        /// </summary>
        internal static string PageCircularHierarcy {
            get {
                return ResourceManager.GetString("PageCircularHierarcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page HTML is mandatory.
        /// </summary>
        internal static string PageHTMLMandatory {
            get {
                return ResourceManager.GetString("PageHTMLMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate page, please try again.
        /// </summary>
        internal static string PageValidationFailed {
            get {
                return ResourceManager.GetString("PageValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition details mandatory.
        /// </summary>
        internal static string RecognitionDetailsMandatory {
            get {
                return ResourceManager.GetString("RecognitionDetailsMandatory", resourceCulture);
            }
        }
    }
}
