//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PagePath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagePath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.PagePath", typeof(PagePath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdateEvent.aspx.
        /// </summary>
        internal static string AdminAddUpdateEvents {
            get {
                return ResourceManager.GetString("AdminAddUpdateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdateGallery.aspx.
        /// </summary>
        internal static string AdminAddUpdateGallery {
            get {
                return ResourceManager.GetString("AdminAddUpdateGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdateHistory.aspx.
        /// </summary>
        internal static string AdminAddUpdateHistory {
            get {
                return ResourceManager.GetString("AdminAddUpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdateNews.aspx.
        /// </summary>
        internal static string AdminAddUpdateNews {
            get {
                return ResourceManager.GetString("AdminAddUpdateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdatePages.aspx.
        /// </summary>
        internal static string AdminAddUpdatePages {
            get {
                return ResourceManager.GetString("AdminAddUpdatePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdateRecognition.aspx.
        /// </summary>
        internal static string AdminAddUpdateRecognitions {
            get {
                return ResourceManager.GetString("AdminAddUpdateRecognitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/AddUpdateResources.aspx.
        /// </summary>
        internal static string AdminAddUpdateResource {
            get {
                return ResourceManager.GetString("AdminAddUpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/Dashboard.aspx.
        /// </summary>
        internal static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/Login.aspx.
        /// </summary>
        internal static string AdminLogin {
            get {
                return ResourceManager.GetString("AdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ManageEvents.aspx.
        /// </summary>
        internal static string AdminManageEvents {
            get {
                return ResourceManager.GetString("AdminManageEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ManageGalleries.aspx.
        /// </summary>
        internal static string AdminManageGalleries {
            get {
                return ResourceManager.GetString("AdminManageGalleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ManageHistories.aspx.
        /// </summary>
        internal static string AdminManageHistories {
            get {
                return ResourceManager.GetString("AdminManageHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ManageNews.aspx.
        /// </summary>
        internal static string AdminManageNews {
            get {
                return ResourceManager.GetString("AdminManageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ManagePages.aspx.
        /// </summary>
        internal static string AdminManagePages {
            get {
                return ResourceManager.GetString("AdminManagePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ManageRecognition.aspx.
        /// </summary>
        internal static string AdminManageRecognitions {
            get {
                return ResourceManager.GetString("AdminManageRecognitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdminShowLogin {
            get {
                return ResourceManager.GetString("AdminShowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewEvent.aspx.
        /// </summary>
        internal static string AdminViewEvent {
            get {
                return ResourceManager.GetString("AdminViewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewGallery.aspx.
        /// </summary>
        internal static string AdminViewGallery {
            get {
                return ResourceManager.GetString("AdminViewGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewHistory.aspx.
        /// </summary>
        internal static string AdminViewHistory {
            get {
                return ResourceManager.GetString("AdminViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewNews.aspx.
        /// </summary>
        internal static string AdminViewNews {
            get {
                return ResourceManager.GetString("AdminViewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewPages.aspx.
        /// </summary>
        internal static string AdminViewPage {
            get {
                return ResourceManager.GetString("AdminViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewRecognition.aspx.
        /// </summary>
        internal static string AdminViewRecognition {
            get {
                return ResourceManager.GetString("AdminViewRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Admin/ViewResource.aspx.
        /// </summary>
        internal static string AdminViewResource {
            get {
                return ResourceManager.GetString("AdminViewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Rules.
        /// </summary>
        internal static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Uploads.
        /// </summary>
        internal static string UploadPath {
            get {
                return ResourceManager.GetString("UploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Uploads.
        /// </summary>
        internal static string UploadWebPath {
            get {
                return ResourceManager.GetString("UploadWebPath", resourceCulture);
            }
        }
    }
}
